name: Run cargo

env:
  CARGO_TERM_COLOR: always

inputs:
  name:
    required: true
  test:
    required: true
  runs-on:
    required: true

runs:
  using: "composite"
  steps:
    - name: Check formatting
      shell: bash
      run: cargo fmt --all -- --check

    - name: Run tests
      if: inputs.test && inpugs.runs-on == 'macos-latest'
      shell: bash
      run: cargo test --verbose

    - name: Build release
      shell: bash
      run: cargo build --release -p dbnet

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: -${{ inputs.name }}
        path: |
          target/release/dbnet
          target/release/dbnet.exe
        retention-days: 5
        if-no-files-found: ignore
