name: "Setup Python"

inputs:
  python-version:
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up specific Python
      if: ${{ inputs.python-version != '' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install maturin
      shell: bash
      run: pip install maturin
