[package]
name = "none"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
interface.workspace = true
anyhow.workspace = true

[dev-dependencies]
criterion = "0.6.0"


[[bench]]
name = "onnx_bench"
harness = false
