[package]
name = "base-util"
version.workspace = true
edition.workspace = true

[dependencies]
ort.workspace = true
ndarray.workspace = true
anyhow.workspace = true
thiserror.workspace = true
opencv.workspace = true
ureq.workspace = true
