name: Push Action

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - name: linux-x86_64
            runs-on: ubuntu-latest
            os: linux
          - name: macos-arm64
            runs-on: macos-latest
            os: macos
          - name: windows-x86_64
            runs-on: windows-latest
            os: windows

    name: Setup on ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ${{ matrix.platform.os }}
        uses: ./.github/actions/setup-${{ matrix.platform.os }}.yml
        with:
          runs-on: ${{ matrix.platform.runs-on }}

      - name: Setup Rust
        uses: ./.github/actions/setup-rust.yml

      - name: Tests & Building
        uses: ./.github/actions/cargo.yml
        with:
          test: false
          name: ${{ matrix.platform.name }}
