name: Push Action

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - name: linux-x86_64
            runs-on: ubuntu-latest
          - name: macos-arm64
            runs-on: macos-latest
          - name: windows-x86_64
            runs-on: windows-latest

    name: Setup on ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Linux
        if: matrix.platform.runs-on == 'ubuntu-latest'
        uses: ./.github/actions/setup-linux
        with:
          runs-on: ${{ matrix.platform.runs-on }}

      - name: Setup macOS
        if: matrix.platform.runs-on == 'macos-latest'
        uses: ./.github/actions/setup-macos
        with:
          runs-on: ${{ matrix.platform.runs-on }}

      - name: Setup Windows
        if: matrix.platform.runs-on == 'windows-latest'
        uses: ./.github/actions/setup-windows
        with:
          runs-on: ${{ matrix.platform.runs-on }}

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Tests & Building
        uses: ./.github/actions/cargo
        with:
          test: false
          runs-on: ${{ matrix.platform.runs-on }}
          name: ${{ matrix.platform.name }}
