name: Push Action

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - name: linux-x86_64
            runs-on: ubuntu-latest
          - name: macos-arm64
            runs-on: macos-latest
          - name: windows-x86_64
            runs-on: windows-latest

    name: Setup on ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Linux
        if: matrix.platform.os == 'linux'
        uses: ./.github/actions/setup-linux.yml
        with:
          runs-on: ${{ matrix.platform.runs-on }}

      - name: Setup macOS
        if: matrix.platform.os == 'macos'
        uses: ./.github/actions/setup-macos.yml
        with:
          runs-on: ${{ matrix.platform.runs-on }}

      - name: Setup Windows
        if: matrix.platform.os == 'windows'
        uses: ./.github/actions/setup-windows.yml
        with:
          runs-on: ${{ matrix.platform.runs-on }}

      - name: Setup Rust
        uses: ./.github/actions/setup-rust.yml

      - name: Tests & Building
        uses: ./.github/actions/cargo.yml
        with:
          test: false
          name: ${{ matrix.platform.name }}
